import Image from "next/image";
import { Shell } from "./Shell";
import { Brand } from "./Brand";
import { siteHref } from "@/lib/site/paths";
import data from "@/content/site/home.generated.json";
export function AboutPage() {
  return <Shell><section className="about-page" data-tone="paper"><div className="v-frame about-intro"><div><p className="label">Richmond, Virginia / RVA3D</p><h1>Rendered with<br /><em>confidence.</em></h1><p className="editorial-lead"><Brand /> is led by Deven Langston, a Richmond-based motion graphic artist with over 20 years of professional experience.</p></div><Image src={data.portrait} width={955} height={1000} alt="Deven Langston, RVA3D founder" unoptimized priority /></div><div className="v-frame studio-story"><p className="label">A direct creative relationship</p><h2>Experienced hands.<br />Room for the unexpected.</h2><p>RVA3D brings together 3D animation, motion graphics, visual effects and interactive media. The common thread is a practical one: understand what the audience needs to see, then build the images and movement that make it clear.</p><p>You work directly with Deven on the creative and technical details. When a project needs additional capacity or specialized expertise, RVA3D brings in trusted independent collaborators and remains responsible for scope, communication and delivery.</p><p>That can mean shaping a sequence from an early idea, developing a convincing product from incomplete references, or solving one demanding shot within a larger production.</p><div className="studio-links"><a className="editorial-link" href={siteHref("/capabilities")}>What you can commission ↗</a><a className="editorial-link" href={siteHref("/work")}>Explore the work ↗</a></div></div></section></Shell>;
}
export function ClientLogin() {
  return <Shell contact={false}><section className="client-placeholder" data-tone="void"><div><Image src={data.logoStill} width={280} height={96} alt="RVA3D" unoptimized priority /><p className="label">For our clients</p><h1>Client login</h1><p className="editorial-lead">The RVA3D client portal is coming soon.</p><p>For an active project, contact Deven through your usual channel or <a href="mailto:hello@rva3d.com">hello@rva3d.com</a>.</p><a className="button" href={siteHref()}>Back to the main site ↗</a></div></section></Shell>;
}
export function PrivacyPage() {
  return <Shell contact={false}><section className="editorial-opening" data-tone="paper"><div className="v-frame privacy-copy"><p className="label">Privacy information</p><h1>Starting a conversation.</h1><p>When enabled for delivery, the inquiry form sends your name, email address, company (if supplied), inquiry type and message to RVA3D through Resend, our email delivery provider. We use those details to respond to your inquiry.</p><p>In this protected preview, ordinary submissions are validated but are not sent. A separately enabled, clearly labeled delivery test sends only to the configured RVA3D recipient. The form uses a hidden spam field and a temporary per-server request limit based on the request IP address.</p><p>The private review uses a signed session cookie to remember successful sign-in. It is restricted to this review area. Hosting and email services may process technical request information as part of operating the site and delivering messages.</p><p>This candidate does not add analytics or marketing cookies. Contact <a href="mailto:hello@rva3d.com">hello@rva3d.com</a> with questions about information you have sent us.</p><a className="editorial-link" href={siteHref("/#contact")}>Back to the inquiry form ↗</a></div></section></Shell>;
}
